### ISSUE TITLE
Convert dataset action to model action

### ISSUE THREAD

**Issue by ricard-inho** [google-deepmind/open_x_embodiment#14]
The inference colab only shows the conversion of dataset action to model action and normalisation for the Bridge dataset. Is it possible to have the code for the rest of the datasets?
Thank you!

**Comment by kpertsch** [comment]
Hi Ricard,

We are working on a code release for an RT-X training pipeline in Jax, which will also include action transformation code for the other datasets in the RT-X mixture, please stay tuned!

**Comment by nikepupu** [comment]
Hi @kpertsch  is there an expected timeline for this?

**Comment by quanvuong** [comment]
Thank you for your patience, we are working to validate the performance of the Jax model, which is why the Jax implementation of  RT-1-X is taking some time to be released.

**Comment by quanvuong** [comment]
The action transformation code for most of the datasets (except QT-OPT and Language Table) is included in https://github.com/google-deepmind/open_x_embodiment/commit/b745d7f84129c467daeca887339d2aaeb23985d3

Please feel free to re-open the issue if you need the action transformation code for these 2 datasets.

**Comment by SashaMalysheva** [comment]
May I ask if you can also share the transformation code for the UIUC D3Field: Kinova Gen3 datasets? I did not find it in the mentioned Colab. Thank you!

**Comment by kpertsch** [comment]
I could find the information re action space for the D3Field dataset, but feel free to reach out to the first authors of the paper for the explanation of the action space in the dataset: https://robopil.github.io/d3fields/
