### ISSUE TITLE
language_embedding of None language description

### ISSUE THREAD

**Issue by rainbow979** [google-deepmind/open_x_embodiment#16]
I have noted that some datasets are marked no language description in the spreadsheets. How to get language embedding for such datasets?

Some (e.g. cable routing dataset) directly used the same language like "cable routing".
How about others?

**Comment by kpertsch** [comment]
All datasets have *some* language instruction stored, so you can always extract that from the fields "language_instruction" and "language_embedding" (which is a continuous embedding vector from a pre-trained sentence embedder). For the datasets that are listed as "no langauge" on the spreadsheet, the language instruction is a constant dummy string like "cable routing" or "pick anything" or "do something".

**Comment by open-x-embodiment** [comment]
The fields are called "*natural_language_instruction*" and "
*natural_language_embedding*" respectively in the "*observation*"
dictionary in each dataset that you can check it out. Specifically for the
cable routing, I believe the instruction is just "*route cable*".
