### ISSUE TITLE
What are the action descriptions?

### ISSUE THREAD

**Issue by datonefaridze** [google-deepmind/open_x_embodiment#17]
Hello, when you deal with robotics (especially when DL is used) it's crutial to have exact definition of actions that model predicts. Currently it predicts something like:
```
{'base_displacement_vertical_rotation': array([-0.00614786], dtype=float32),
  'rotation_delta': array([-0.00307393, -0.00307393, -0.00307393], dtype=float32),
  'base_displacement_vector': array([-0.00195694, -0.00195694], dtype=float32),
  'world_vector': array([-0.00391388, -0.00391388, -0.00391388], dtype=float32),
  'terminate_episode': array([0, 1, 0], dtype=int32),
  'gripper_closedness_action': array([1.], dtype=float32)}
  ```
  but this is still vague to me what each component exactly means. As i currently understand world_vector_1,2,3 are translation from base/or from the world till gripper, and rotation_delta_1,2,3 means rotations towards each axis (am i correct?) but what does those terminate episodes mean?
Can you please help me to understand those?

**Comment by kpertsch** [comment]
Please check the RT-1-X inference Colab. The terminate_episode is a one-hot representation of whether the agent thinks the current timestep finishes the instructed skill and can be used to terminate an episode.

![image](https://github.com/google-deepmind/open_x_embodiment/assets/15955682/a039d495-989e-4f91-899f-4555e9e818b6)

Basically `[1, 0, 0]` means that the model thinks the timestep is a terminate timestep (skill is complete), `[0, 1, 0]` means it's *not* a terminate timestep and execution should continue.

**Comment by datonefaridze** [comment]
@kpertsch thanks a lot, i missed that part. Also don't we have to apply pre-processing to images before it is inputted in the model? as i see in the code, the images are directly fed to tensorflow agents (as long as i know tf agents doesn't provide inner pre-processing?)

**Comment by quanvuong** [comment]
For image pre-processing before the image is fed into the model, please refer to the inference colab, which includes all necessary image pre-processing.

**Comment by datonefaridze** [comment]
@quanvuong i saw it, the only pre-processing that is applied is resizing. When i print the pixel values before they are fed to the model they range from 0-255.

**Comment by datonefaridze** [comment]
@SashaMalysheva hello, I never managed to use this model, didn't use it, i ended up using facebook model, this one: https://github.com/facebookresearch/eai-vc
It worked perfectly, I solved robotics problem using that

**Comment by SashaMalysheva** [comment]
@datonefaridze, thank you! Will check it :-) 

May I ask on which model of robotic arms you checked it? Is it 5 DOF+gripper?

**Comment by datonefaridze** [comment]
@SashaMalysheva This is my repo: https://github.com/datonefaridze/inverse_kinematics_xarm/tree/master it has 6 DOF + gripper. But for the new solution i used inverse kinematics.
