### ISSUE TITLE
Can the model be fine-tuned?

### ISSUE THREAD

**Issue by reginald-mclean** [google-deepmind/open_x_embodiment#21]
Hi! Thank you so much for providing the model checkpoint and starter code to use the model. Is it possible to fine tune the RT1-X model? We are having some issues applying the model to our environment, but fine-tuning it could fix the issue. Thanks in advance!

**Comment by open-x-embodiment** [comment]
Hi!
It should be possible to finetune the RT-1-X model on your own. Can
you please elaborate what issues you are facing?
Also, we are hoping to release Jax code with example finetuning code. That
should be a nice reference code for that.

Best,
Pannag

**Comment by reginald-mclean** [comment]
I am attempting to use RT-1-X model in [Meta-World](https://github.com/Farama-Foundation/Metaworld/). I used the code from the minimal example notebook to load and use the policy. Meta-World has an action space of size 4, the desired xyz position of the end effector and a scalar value that indicates how open/close the gripper should be. I took the base displacement, base displacement vertical, and gripper open/close values from the policy action dictionary and use those as the action (concatenated together). However, I am not seeing any tasks being solved with this method.

**Comment by quanvuong** [comment]
Hi Reggie,

For the RT-1-X model, we currently do not expect the model to zero-shot solve manipulation problems in a new domain that the model was not trained on (such as Meta World).

The base displacement and base displacement vertical are also intended to control the base movement of a robot, and not the xyz position of the end effector.
