### ISSUE TITLE
Downloading 'bridge' Dataset using tfds-nightly

### ISSUE THREAD

**Issue by Wolfwjs** [google-deepmind/open_x_embodiment#25]
Hello,

I am encountering an issue while trying to download the `bridge` dataset using TensorFlow Datasets (TFDS). I am currently using tfds-nightly version 4.9.3.dev202311230044.

### Issue Description
When I attempt to load the 'bridge' dataset with the following code:
```
import tensorflow_datasets as tfds
tfds.load('bridge', data_dir="mypath/“)
```
I receive an error indicating that the dataset cannot be downloaded.

In addition to the issue described above, I am considering the possibility of manually downloading the dataset from the following URL:
https://rail.eecs.berkeley.edu/datasets/bridge_release/data/tfds/bridge_dataset/1.0.0/

Before I proceed with this approach, I have a few questions:

1. Is manually downloading the dataset from this URL a recommended solution to the problem I am experiencing?

2. Will manually downloaded data integrate seamlessly with the TensorFlow Datasets API, or are there additional steps required to ensure compatibility?

Any guidance or suggestions regarding manual downloading would be greatly appreciated.

Thank you!

**Comment by quanvuong** [comment]
Raise the issue to tfds team here https://github.com/tensorflow/datasets/issues/5170

**Comment by Wolfwjs** [comment]
Hi @kpertsch , thank you for your suggestion. I would like to confirm, if I use the command `gsutil -m cp -r gs://gresearch/robotics/bridge/0.1.0 /mypath/`, does it download the latest bridge v2 data?

**Comment by Wolfwjs** [comment]
Perfect, the Bridge v2 dataset is exactly what I need. Additionally, could you please explain what is meant by "lacks the additional camera streams"? Does this refer to a lack of image or video data?

**Comment by Wolfwjs** [comment]
Thank you for your patient response! I look forward to your updates, and for now, I will start with a single camera stream.
