### ISSUE TITLE
Question about "Minimal_Training_Example.ipynb"

### ISSUE THREAD

**Issue by litchiyj** [google-deepmind/open_x_embodiment#26]
1.Why do different datasets have different processing methods？
a: taco_play，bridge dataset have rescale_action funcion，but their  values of [high，low，post_scaling_max,post_scaling_min] is different
b: jaco_play dataset have _normalize function（mean，std）
c: berkeley_cable_routing，roboturk dataset  have no special processing
d:nyu_door_opening，viola  berkeley_autolab_ur5，toto  dataset  have scale by different number

The values of world_vecter and rotation are relatively small, and they feel like relative coordinates.
The purpose of processing is to put world_vecter and rotation into the same interval  [-2,2]  ,[-1,1]？

**Comment by quanvuong** [comment]
The purpose of processing is to put world_vecter and rotation into the same interval ? Yes, the purpose of processing is to put world_vecter and rotation into **roughly** the same interval

**Comment by litchiyj** [comment]
1. Is **roughly** the same interval necessary? Can this approach speed up model convergence? It feels like there is no essential change.
2. Different data sets are processed in different ways. Is there any basis for this?
 Thanks  @quanvuong

**Comment by litchiyj** [comment]
> 1. I did it because it prevents too many neighboring actions in continuous space being collapsed into a single token, given a fixed vocab size and domain used for tokenizing the continuous actions.
> 2. Different datasets are processed different ways because the magnitudes of the action vary across the different datasets.

Can you elaborate on point 2? Why jaco_play data set is _normalize function(mean, std) while berkeley_autolab_ur5 data set is scale by number.
Can't the berkeley_autolab_ur5 data set also be processed with the _normalize function?  thanks very much

**Comment by litchiyj** [comment]
> Could you please clarify what physical quantity the `world_vector` specifically represents? Is it position, velocity, or acceleration? Also, does `rotation_delta` represent rotation? What are the units for each of these measurements?

There is some information, but not complete。https://www.tensorflow.org/datasets/catalog/viola

**Comment by SashaMalysheva** [comment]
@litchiyj I checked the provided links and found that they do not describe the order of the model's output or the specific arrangement of the x, y, and z coordinates. And maybe you know which components of the rotation_delta correspond to roll, pitch, and yaw?
