### ISSUE TITLE
Scaling the Datasets

### ISSUE THREAD

**Issue by Shinechaote** [google-deepmind/open_x_embodiment#28]
Hey, 
in your taco action mapper you use the _rescale_action method defined for the bridge dataset. In there you assume the world vector values to be in [-0.05,0.05]. When I look at the taco-paper  ("Latent Plans for Task-Agnostic Offline Reinforcement Learning") however they say, that the action values are in [-1, 1]. 
We are currently trying to scale the actions to be in [0, 255] to tokenize them and are therefore a little confused.
Are the action values of the taco dataset in [-0.05,0.05] or in [-1, 1]? Also why did you define the taco_play_rescale_action and then did not use it?
Also if you have them, could you please release the ranges of the action values for the other datasets? Otherwise we would have to iterate through the datasets to find them.

**Comment by kpertsch** [comment]
Please find the action statistics per dimension for Taco below (note I am showing `rel_actions_world` here, I believe there is also an absolute action field which may be where the confusion is coming from) :
```
"mean": [-0.0023318706080317497, 0.007663276512175798, 0.01230847928673029, -0.004802674520760775, -0.00975735578685999, -0.004280156921595335, 0.4284927248954773]
"std": [0.23156508803367615, 0.3645283281803131, 0.28797319531440735, 0.2616391181945801, 0.2437218874692917, 0.5219944715499878, 0.4949808716773987]
"max": [1.4915844202041626, 2.1842432022094727, 2.6836395263671875, 5.035226821899414, 2.665864944458008, 4.250768661499023, 1.0]
"min": [-4.242457866668701, -3.192805051803589, -1.3371467590332031, -4.202683448791504, -2.6722638607025146, -3.3467135429382324, 0.0]}
```

I quickly visualized the actions in this Colab: https://colab.research.google.com/drive/1OdiOgOhZhG9nuSN26Ph-UxBVHDfa9olE?usp=sharing

Most of them indeed seem to be in the -1...1 range.
![image](https://github.com/google-deepmind/open_x_embodiment/assets/15955682/61b2fdfe-8706-46b1-b303-e619a62bb36f)

If you want to get the statistics for all datasets (like the ones I posted above) you can check out the [Octo](https://octo-models.github.io/) data loader, it computes them on the fly + has an [action tokenizer](https://github.com/octo-models/octo/blob/566d77588bd70fcd2fac785d4162f2d29e7bf634/octo/model/components/tokenizers.py#L233) that supports the kind of discretization you mentioned!

**Comment by Shinechaote** [comment]
Thank you very much and also thanks for your work on Octo. I have been working with the Octo Dataloader since Monday and didn't even know about the BinTokenizer but that definitely makes it a bit easier than the way I implemented it.

**Comment by zhang2514yuchi** [comment]
> Please find the action statistics per dimension for Taco below (note I am showing `rel_actions_world` here, I believe there is also an absolute action field which may be where the confusion is coming from) :
> 
> ```
> "mean": [-0.0023318706080317497, 0.007663276512175798, 0.01230847928673029, -0.004802674520760775, -0.00975735578685999, -0.004280156921595335, 0.4284927248954773]
> "std": [0.23156508803367615, 0.3645283281803131, 0.28797319531440735, 0.2616391181945801, 0.2437218874692917, 0.5219944715499878, 0.4949808716773987]
> "max": [1.4915844202041626, 2.1842432022094727, 2.6836395263671875, 5.035226821899414, 2.665864944458008, 4.250768661499023, 1.0]
> "min": [-4.242457866668701, -3.192805051803589, -1.3371467590332031, -4.202683448791504, -2.6722638607025146, -3.3467135429382324, 0.0]}
> ```
> 
> I quickly visualized the actions in this Colab: https://colab.research.google.com/drive/1OdiOgOhZhG9nuSN26Ph-UxBVHDfa9olE?usp=sharing
> 
> Most of them indeed seem to be in the -1...1 range. ![image](https://private-user-images.githubusercontent.com/15955682/292268468-61b2fdfe-8706-46b1-b303-e619a62bb36f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NzIzMzEsIm5iZiI6MTcxNzY3MjAzMSwicGF0aCI6Ii8xNTk1NTY4Mi8yOTIyNjg0NjgtNjFiMmZkZmUtODcwNi00NmIxLWIzMDMtZTYxOWE2MmJiMzZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDExMDcxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExZGUyYmYzYjkyNjcxYzg1MGE0NjZlMTk3YWMyMWEyMzZiYzBjMDBkYTZhMGQwNWMzMmUxN2U3Y2NjNzAzNDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8R1vjMccIOb9N_7MRafNMsGSt18D5OiF6BZMzOHQbJ0)
> 
> If you want to get the statistics for all datasets (like the ones I posted above) you can check out the [Octo](https://octo-models.github.io/) data loader, it computes them on the fly + has an [action tokenizer](https://github.com/octo-models/octo/blob/566d77588bd70fcd2fac785d4162f2d29e7bf634/octo/model/components/tokenizers.py#L233) that supports the kind of discretization you mentioned!

I want to use the model trained by Droid dataset to do inference in the real environment. If there is a regularization operation, we may need to reverse the regularization.
I couldn't find any information about the droid datasets. I want to know if the raw data is normalized, and if so, how it is normalized.

**Comment by kpertsch** [comment]
See my answer to your question in the DROID dataset repo!
