### ISSUE TITLE
Discrepancy in the number of trajectories parsed from the bridge dataset

### ISSUE THREAD

**Issue by Wolfwjs** [google-deepmind/open_x_embodiment#30]
I have parsed all the `bridge-train.tfrecord-xxx-of-01024` files from the bridge dataset, but I only obtained 25,460 trajectories. However, the [bridge v2](https://rail-berkeley.github.io/bridgedata/) mentions that there are a total of 60,000 trajectories. Can you please explain the reason for this significant difference in the number of trajectories?

**Comment by kpertsch** [comment]
The OXE version of BridgeV2 was uploaded at an early stage of the project and does not include all Bridge trajectories of their final release. We are planning to update it to the most recent version, but in the meantime please use the RLDS-converted version of the Bridge dataset from the original authors (https://rail.eecs.berkeley.edu/datasets/bridge_release/data/tfds/bridge_dataset/) -- this one should have all trajectories included!

**Comment by kpertsch** [comment]
Sorry I just realized that we discussed about the Bridge dataset 2 weeks ago already. I just recently realized the discrepancy in the number of trajectories when we worked on the Octo release, before we always used the "original" version of the Bridge dataset for our internal development so I didn't realize the OXE one was lacking data. Sorry for the inconvenience!!
