### ISSUE TITLE
Difference between language_table 0.0.1 and 0.1.0

### ISSUE THREAD

**Issue by Wolfwjs** [google-deepmind/open_x_embodiment#31]
I noticed that there are two versions of the `language_table` dataset: 0.0.1 and 0.1.0. Can you please clarify the differences between these two versions? Is version 0.1.0 a newer update, and is it recommended for use over version 0.0.1?

**Comment by kpertsch** [comment]
I believe the different versions of language_table were uploaded by the original authors and I am not fully sure what is the difference between them. From a quick comparison of the `features.json` files I couldn't see an obvious difference. For our experiments in [Octo](https://octo-models.github.io/) we used the v0.1.0 and I think this is a safe default to go with!

**Comment by Wolfwjs** [comment]
Thank you for your response! I will check out Octo.

**Comment by psanketi** [comment]
Checked with the authors, they both are the same.
