### ISSUE TITLE
Natural language embeddings not added in observation in Minimal_example_for_running_inference_using_RT_1_X_TF_using_tensorflow_datasets.ipynb

### ISSUE THREAD

**Issue by lakomchik** [google-deepmind/open_x_embodiment#4]
Hello! Thank you for sharing datasets and model weights. I have a question about model inference in Minimal_example_for_running_inference_using_RT_1_X_TF_using_tensorflow_datasets.ipynb.
In example, you add only an image in observation which one then feeded to model. But there are also natural language instruction and natural language embeddings in the dataset. Do they should be added to observation in model inference?

**Comment by datonefaridze** [comment]
@lakomchik hello, I also have this problem
