### ISSUE TITLE
JAX/FLAX Checkpoint Release

### ISSUE THREAD

**Issue by BakedNotFried** [google-deepmind/open_x_embodiment#41]
Are there plans to release a JAX/FLAX checkpoint that can be used by the flax checkpoint loader in the rt1_inference_example.py?

**Comment by psanketi** [comment]
Hello, yes, sorry we forgot to update the documentation! The checkpoint is at:
gs://gdm-robotics-open-x-embodiment/open_x_embodiment_and_rt_x_oss/rt_1_x_jax/
Pl let us know if you can access it all right. 

Best,

- Pannag

**Comment by BakedNotFried** [comment]
Thanks for that! I can access it and run the inference script :)
